name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Deploy sin build
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "/"                 # carpeta raíz de tu HTML/CSS/JS
          api_location: ""                  # si no usas Functions
          output_location: ""               # también vacío; despliega todo app_location
          skip_app_build: true              # ¡importante!
